---
# tasks file for provision/roles/django

- name: install pip
  yum:
    name: 
      - python-pip
      - python-devel
      - gcc
    state: present

- name: upgrade pip
  pip:
    name: pip
    state: forcereinstall

- name: upgrade setuptools
  pip:
    name: setuptools
    state: forcereinstall

- name: install django from pip
  pip:
    name: Django

- name: install uwsgi from pip
  pip:
    name: uwsgi

- name: add user 'django'
  user:
    name: django
    group: nginx
    shell: /bin/bash
    home: /var/www/django
    system: yes

- name: create dir django
  file:
    path: /var/www/django
    state: directory
    mode: '0770'
    owner: django
    group: nginx

- name: create django project
  shell: |
    cd /var/www/django
    touch testfile.txt
    django-admin startproject otus
    cd /var/www/django/otus
    python manage.py migrate
  become_user: django

- name: allow connection to django
  lineinfile:
    path: /var/www/django/otus/otus/settings.py
    regexp: '^ALLOWED_HOSTS'
    line: "ALLOWED_HOSTS = ['192.168.56.10']"
  become_user: django

- name: create uwsgi dir
  file:
    path: /etc/uwsgi/sites
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: copy uwsgi config
  copy:
    src: otus.ini
    dest: /etc/uwsgi/sites/otus.ini
    owner: root
    group: root
    mode: 0644

- name: copy uwsgi systemd unit
  copy:
    src: uwsgi.service
    dest: /etc/systemd/system/uwsgi.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart uwsgi

- name: copy uwsgi nginx config
  copy:
    src: uwsgi.conf
    dest: /etc/nginx/conf.d/uwsgi.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

