---
# vars file for provision/roles/laravel

required_packages:
  - unzip
  - libselinux-python

php_packages: 
  - php-fpm 
  - php-cli 
  - php-mysql 
  - php-gd 
  - php-ldap 
  - php-odbc 
  - php-pdo 
  - php-pecl-memcache 
  - php-pear 
  - php-xml 
  - php-xmlrpc 
  - php-mbstring 
  - php-mcrypt
  - php-snmp 
  - php-soap

